# Generated by Django 3.2.7 on 2021-09-03 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=200)),
                ('publication', models.CharField(blank=True, max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('date_published', models.DateField(verbose_name='Date published')),
                ('body', models.TextField(blank=True, default='', max_length=5000)),
                ('notes', models.TextField(blank=True, default='', max_length=3000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
