# Generated by Django 3.2.7 on 2021-09-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='article',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=3000),
        ),
    ]
