# Generated by Django 3.2.7 on 2021-09-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_date_article_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(blank=True, default='', max_length=60000),
        ),
        migrations.AlterField(
            model_name='article',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=30000),
        ),
    ]
